## 
1. 引入异常用来解决什么问题
a. 可以减少通过返回值的方式通知调用方方法调用出现问题。可以将正常的流程的代码和处理异常情况的代码隔离开。有利于代码扩展。对于增加新的异常的处理、或者修改以往的异常处理方式都更方便。
b. 可以对模块化的内部异常进行隐藏，对外暴露有限个异常。对于方法调用方和模块的使用对于异常的处理更加清晰。
2. java异常如何分类。
a. Exception 的子类，受查异常(check exception)，如果是在代码内抛出此类异常，异常必须进行处理，可以代码中进行catch处理，或者在方法中通过throws声明向外抛出。包括main方法也可以throws异常向上抛出，抛出后由jvm进行处理。
b. RuntimeException的子类，非受查异常(uncheck exception)，可以不处理，不处理则沿着方法的调用依次向上抛出。直到有catch处理，或者抛出到main方法外部由jvm处理。
3. 何时需要抛出异常，何时需要捕获处理异常
通知调用方方法调用失败。 如果需要对方法调用失败的情况进行处理，这时候需要捕获异常，如果当前方法不确定如何处理异常，可以再次将异常抛出。
4. 何时需要抛出受查异常，何时需要抛出非受查异常
如果造成方法调用失败的原因，如果来自于方法调用方，则抛出非受查异常。如果造成方法调用失败的原因来自于方法依赖的其他方法，通常是指依赖外部功能的方法(例如网络、文件)，抛出受查异常。
5. 抛出异常后，后续代码的运行顺序是否受到影响
受到影响，抛出异常的后续代码不再执行，如果捕获异常，则执行捕获异常后的处理代码(catch代码块中的内容)。如果需要在异常出现与否都需要执行某些代码，可以将这部分代码放置在finally代码块中。

# 前置知识

* 类和对象基础
* 类的继承

# 课程结构

首先介绍异常的相关概念，然后介绍异常分类，如何定义和抛出异常。如何处理异常，最后介绍发生异常后关闭异常的方式

# 学习目标

- 学会自定义异常(受查和非受查)
- 学会抛出异常
- 学会处理异常

# 异常

在理想状态下，用户输入数据的格式永远都是正确的，选择打开的文件一定会存在，程序运行都是按照预期没有bug的，但事实上，以上的情况都无法保证，作为一个程序设计人员，要尽可能的预知所有可能发生的情况，尽可能的保证程序在所有糟糕的情形下都可以运行，我们希望程序在遇到一些异常的时候，至少能够返回到一种状态能让用户执行一些其他命令，或者允许用户保存当前的操作结果，并且以妥善的方式终止程序。

假设你需要设计一个方法，这个方法接收一个用户输入的String参数，然后返回给用户一个处理结果，当你在方法内部使用这个String参数的时候，需要考虑，如果是个null怎么办，如果包含了空格怎么办，如果长度超出了要求限制怎么办，如果包含了特殊字符怎么办，如果都想明白了如何处理之后，还需要考虑，当出现上述问题后，如何告知调用这个方法的人传入的参数不合理。

这时可能遭遇两个问题，一个是判断异常的逻辑代码增多，可能和正常流程的业务代码交杂在一起不好分离。另一个是需要提供额外的返回标志调用方出现了什么问题。

通常我们更希望处理异常的代码和业务逻辑代码分离开，有专门的异常机制可以告诉调用方出现了异常，并且是什么样子的异常。

异常机制已经成为判断一门编程语言是否成熟的标准，除传统的像C语言没有提供异常机制外，很多语言像Java,C++,Python,Ruby等都提供了成熟的异常机制

## java异常机制

java的异常机制主要是被调用函数在执行中遇到了问题则停止继续向下执行，然后`抛出异常`结束调用，调用方通过`捕获异常`到指定的处理异常的代码区域进行统一处理。

## 异常分类

抛出、捕获的都是异常的对象，因此需要有异常类。所有的异常类都继承自`java.lang.Throwable`, 这个类有两个直接的子类，`java.lang.Error`和`java.lang.Exception`。

- Error 用于描述java运行时系统的内部错误和资源好近错误。应用程序不应该抛出这种类型的对象。如果出现了这样的内部错误，除了通知用户，并尽力使程序安全终止之外，再也无能为力了，这种情况很少出现。
- Exception 有两个分支
  - 一个分支是其子类`java.lang.RuntimeException`以及它的后代，表示由程序错误导致的异常，比如错误的类型转换、数组访问越界、访问null指针、枚举的valueOf没有找到对应的对象
  - 另一个分支是所有非`java.lang.RuntimeException`及其子类的类，表示受到外部制约而产生的异常，比如打开一个不存在的文件、网络连接中断

Error和RuntimeException被称作非受查异常（unchecked Exception）,其他的Exception子类被称作受查异常（checked Exception）

> 如果出现RuntimeException，那么就是调用方的问题，出现checkedException，那么就是被调用方内部出了问题。

# 抛出异常

## 方法声明抛出异常类

在方法声明尾部使用`throws`声明需要抛出的异常类,只有`受查异常`才需要进行抛出异常声明，抛出多个异常需要使用`,`隔开

语法

```
访问修饰符 返回值 方法名() throws 异常类名 {
    语句
}
// 只有受查异常才需要声明抛出
public void checkedExceptionMethod() throws IOException {

}

// 非受查异常不需要声明抛出，虽然编译不报错，但是没有必要这么写
public void uncheckedExceptionMethod() throws RuntimeException {

}

// 一次抛出多个异常，使用逗号隔开
public void checkedMultipleExceptionMethod() throws IOException, SQLException {

}
```

## 方法内抛出异常对象

在方法内部使用`throw`抛出异常对象，如果抛出的是受查异常，则必须由对应的异常声明在方法上。如果抛出的是非受查异常，则不需要方法声明上有异常类的描述。一旦抛出了异常，`throw`下面的语句将不会被执行，方法也不会返回值给调用方。抛出异常的动作总结为:

1. 找到合适的异常类
2. 创建这个类的对象
3. 将对象抛出

```
访问修饰符 返回值 方法名() throws 异常类名 {
    语句...
    
    throw 异常类的对象;
    
    语句...
}
```

示例代码

```
  // 非受查异常不需要方法声明
  public void setHeight(int height) {
    if (height <= 0) {
      throw new UnsupportedOperationException("高度不合法");
    }
  }

  // 受查异常需要方法声明抛出的异常类
  public void openFile(File file) throws FileNotFoundException {
    if (file == null || !file.exists()) {
      throw new FileNotFoundException("文件未找到");
    }
  }
```

### 自定义异常类

当没有合适预定义的异常类可以描述清楚问题的时候，可以使用自定义异常类。自定义的类只需要继承自Exception或RuntimeException或这两个类的子类即可。

# 捕获异常

捕获异常是将方法抛出的异常进行处理，捕获后运行指定位置的代码。对于非受查异常，一旦抛出，会沿着方法的调用路径依次向上，如果都没有捕获处理这个异常，则当前线程将终止，如果调用方是在main方法中，整个程序将退出。受查异常需要每级方法都要声明抛出异常，不然就会编译失败。如果都抛出没有方法捕获的话，最后也会到main方法中，如果main方法也抛出受检异常，那么当受检异常发成后，程序也会终止。

## try/catch 捕获异常

```
try {
    语句
} catch(异常类数据类型 对象名) {
    异常处理的代码
}
```

如果try中抛出了catch中声明的类型的异常，那么代码会跳过try语句块的其他代码执行catch中的处理异常的代码

## 捕获多个异常

在一个try/catch中可以捕获多个异常类型，并根据不同类型做出相应处理

```
try {
    语句
} catch (异常类数据类型1 对象名) {
    异常处理的代码
} catch (异常类数据类型2 对象名) {
    异常处理的代码
} catch (异常类数据类型3 对象名) {
    异常处理的代码
}
```

java7之后，当异常类之间没有父子关系的时候，可以合并catch子句，合并后的对象名为final类型

```
try {
    语句
} catch (异常类数据类型1 | 异常类数据类型2 对象名) {
    异常处理的代码
} catch (异常类数据类型3 对象名) {
    异常处理的代码
}
try {
    ... // 抛出异常的代码
} catch(IOException e) {
    e = new IOException();  // 编译通过，但是不要这么做
    e.printStackTrace();
}

try {
    ... // 抛出异常的代码
} catch(IOException | ParserException e) {
    e = new IOException(); // 编译不通过, 因为这里的e是final类型
    e.printStackTrace();
}
```

## catch后再次抛出异常

catch语句中同样可以抛出异常，这样做的目的是为了改变异常的类型。将内部的细节隐藏起来。

```
try {
    ... // 抛出异常的代码
    // 使用initCause 将原始异常信息包装起来
} catch(ParserException e) {
    e.printStackTrace();
    IOException ioException = new IOException();
    ioException.initCause(e);
    throw ioException;
}
```

### 受查异常包装成非受查异常抛出

有些情况不允许抛出异常，比如继承父类的方法没有抛出异常，那么子类也不许抛出异常，这个时候可以catch 受查异常，然后包装称为非受查异常抛出。

### 异常的堆栈信息

使用 `e.printStackTrace();` 将异常的堆栈信息输出到控制台。里面包含了发生异常的时候方法的调用路径。

## finally

出现异常的方法后续代码不会被执行了，有时候我们希望能够执行一些退出时候的清理动作，比如关闭一些资源等，这些代码可以放到finally代码块中执行

```
try {
    ... // 抛出异常的代码
} catch(ParserException e) {
    e.printStackTrace();
} finally {
    // 执行关闭资源动作
}
    Gate gate = new Gate();
    try {
       gate.open();
       // 业务逻辑代码
    } catch (GateBrokeException e) {
       e.printStackTrace();
    } finally {
       if (gate.isOpen()) {
         try {
           gate.close();
        } catch (GateBrokeException e) {
           e.printStackTrace();
        }
    }
```

### 执行顺序

try语句抛出异常，catch语句运行结束之后，运行finally的代码块，如果try中或catch中有return语句，那么在return语句执行之前，将执行finally中内容，如果finally中也有return语句，则返回值是finally return的值。如果finally中有return语句，那么catch语句块中抛出的异常将被屏蔽掉，不会被方法调用方感知。

## 带资源的try

java7之后，提供了更方便的关闭资源的方式，将创建资源实例的语句放到try()中，这样被创建出来的资源只要其类实现了`java.lang.AutoCloseable`接口，就可以自动关闭，不再需要在finally里面释放。在try代码块结束后，将会调用资源close()方法，close方法是需要实现`java.lang.AutoCloseable`接口必须实现的方法。

```
try(Resource res = new Resource()){
    
}
```

可以同时创建多个对象，只要类实现了AutoCloseable接口。在结束后依次调用close方法

```
try(Resource res1 = new Resource(); Resource res2 = new Resource()){
    
}
```

如果try中抛出了异常，那么在抛出异常之前，先执行close方法将资源关闭，如果close方法执行的时候也抛出了异常，那么这些异常将被调用将会调用 e.addSuppressed(),将异常添加到try中抛出的异常内部，使用e.getSuppressed()获取添加进来的异常列表